"""Ledger + verdicts -> PROOF.md.

    python proofs/stats.py --root <harness root> [--out PROOF.md]

Reads runs/ledger.jsonl for the run list and joins each run's verdict.json /
outcome.json. The headline numbers separate the agent's claim (run status) from
the harness verdict (verifier pass rate) — that gap is the product.
"""

import argparse
import json
import sys
from pathlib import Path


def collect(root):
    root = Path(root)
    ledger_path = root / "runs" / "ledger.jsonl"
    if not ledger_path.exists():
        return []
    rows = []
    for line in ledger_path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        rec = json.loads(line)
        run_dir = root / "runs" / rec["run_id"]
        verdict, outcome = {}, {}
        if (run_dir / "verdict.json").exists():
            verdict = json.loads((run_dir / "verdict.json").read_text(encoding="utf-8"))
        if (run_dir / "outcome.json").exists():
            outcome = json.loads((run_dir / "outcome.json").read_text(encoding="utf-8"))
        rows.append({
            "run_id": rec["run_id"],
            "goal": rec.get("goal", "?"),
            "status": rec.get("status", "?"),
            "cost_usd": rec.get("total_cost_usd") or 0.0,
            "verdict_passed": verdict.get("passed"),
            "verifier_count": len(verdict.get("verifiers", [])),
            "failures": outcome.get("failures", []),
            "model": rec.get("model"),
        })
    return rows


def render(rows, notional_cost=False):
    n = len(rows)
    if not n:
        return "# PROOF\n\nNo runs recorded yet.\n"
    success = sum(1 for r in rows if r["status"] == "SUCCESS")
    judged = [r for r in rows if r["verifier_count"]]
    verified = sum(1 for r in judged if r["verdict_passed"])
    cost = sum(r["cost_usd"] for r in rows)
    pct = f"{100 * verified / len(judged):.0f}%" if judged else "n/a"

    lines = [
        "# PROOF — independently verified agent runs",
        "",
        f"- **Tasks run:** {n}",
        f"- **Runs succeeded:** {success}/{n}",
        f"- **Independently verified pass:** {verified}/{len(judged)} ({pct})"
        + (" — every task judged by verifiers, not by the agent's claim"
           if judged else ""),
    ]
    # Only claim a model when every run agrees on one; a mixed or unrecorded set
    # would make the line a guess.
    models = {r["model"] for r in rows}
    if len(models) == 1 and None not in models:
        lines.append(f"- **Model:** `{models.pop()}`")

    # A subscription-billed run spends no per-token money, so its ledger figures
    # are what the tokens *would* have cost at API rates. Publishing those as
    # costs would be a claim the artifacts do not support.
    if notional_cost:
        lines.append(
            "- **Cost:** withheld — this run was billed to a Claude subscription, "
            "not per-token API credit, so the ledger's dollar figures are notional "
            "and are not published as costs."
        )
    else:
        lines.append(f"- **Total cost:** ${cost:.4f} (${cost / n:.4f}/task)")

    header = "| run | goal | status | harness verdict |"
    lines += ["", header if notional_cost else header + " cost |",
              "|---|---|---|---|" if notional_cost else "|---|---|---|---|---|"]
    for r in rows:
        verdict = ("PASS" if r["verdict_passed"] else "FAIL") \
            if r["verifier_count"] else "no verifiers"
        row = (f"| {r['run_id']} | {r['goal']} | {r['status']} "
               f"| {verdict} ({r['verifier_count']}) |")
        lines.append(row if notional_cost else row + f" ${r['cost_usd']:.4f} |")
    lines += ["", "Generated by `proofs/stats.py` from `runs/ledger.jsonl` "
                  "and per-run `verdict.json` — the artifacts, not the transcript.", ""]
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", default=".", help="harness root (runs/)")
    parser.add_argument("--out", default=None, help="output path (default <root>/PROOF.md)")
    parser.add_argument("--notional-cost", action="store_true",
                        help="subscription-billed run: withhold cost instead of publishing it")
    args = parser.parse_args(argv)

    root = Path(args.root)
    out = Path(args.out) if args.out else root / "PROOF.md"
    text = render(collect(root), args.notional_cost)
    out.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
